services:
  node-app:
    image: node-app:1.0
    container_name: node-app
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./sample.txt:/app/sample.txt
    networks:
      - my-network

networks:
  my-network:
    name: my-network
    driver: bridge
