name: Build and Publish QA Docker Image

on:
  push:
    branches: [qa]
  pull_request:
    branches: [qa]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image for QA
        run: |

      - name: Print status
        run: echo "Successfully pushed qa-latest image"
