name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   
          token: ${{ secrets.GH_NEW_PAT }} 

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_NEW_PAT }}
        # run: |
        #   git config user.name "github-actions[bot]"
        #   git config user.email "github-actions[bot]@users.noreply.github.com"
        #   git pull origin main --rebase   
        #   npx semantic-release
